-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 10:59:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Marca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Marca` (
  `idMarca` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo de Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tipo de Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tipo de Producto` (
  `idTipo de Producto` INT NOT NULL,
  `Tipo de Productocol` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idTipo de Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Codigo Producto` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL(10) NOT NULL,
  `Cantidad` VARCHAR(30) NOT NULL,
  `Stock_Max` VARCHAR(20) NOT NULL,
  `Stock_Min` VARCHAR(20) NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  `Tipo de Producto_idTipo de Producto` INT NOT NULL,
  PRIMARY KEY (`Codigo Producto`),
  INDEX `fk_Producto_Marca1_idx` (`Marca_idMarca` ASC),
  INDEX `fk_Producto_Tipo de Producto1_idx` (`Tipo de Producto_idTipo de Producto` ASC),
  CONSTRAINT `fk_Producto_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `mydb`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Tipo de Producto1`
    FOREIGN KEY (`Tipo de Producto_idTipo de Producto`)
    REFERENCES `mydb`.`Tipo de Producto` (`idTipo de Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `Numero` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(10) NOT NULL,
  `Email` VARCHAR(15) NOT NULL,
  `Direccion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL,
  `Pasword` VARCHAR(10) NOT NULL,
  `Numero` VARCHAR(10) NOT NULL,
  `Correo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(10) NOT NULL,
  `Direccion` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_Administrador_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Administrador_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `Persona_idPersona1` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `Persona_idPersona`),
  INDEX `fk_Empleado_Persona1_idx` (`Persona_idPersona1` ASC),
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`Persona_idPersona1`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Sub_Total` DECIMAL(15) NOT NULL,
  `Iva` DECIMAL(10) NOT NULL,
  `Total` DECIMAL(15) NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Empleado_Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Empleado1_idx` (`Empleado_idEmpleado` ASC, `Empleado_Persona_idPersona` ASC),
  CONSTRAINT `fk_Venta_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado` , `Empleado_Persona_idPersona`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado` , `Persona_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_has_Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto_has_Venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto_has_Venta` (
  `Producto_Codigo Producto` INT NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  `Controles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_Codigo Producto`, `Venta_idVenta`),
  INDEX `fk_Producto_has_Venta_Venta1_idx` (`Venta_idVenta` ASC),
  INDEX `fk_Producto_has_Venta_Producto1_idx` (`Producto_Codigo Producto` ASC),
  CONSTRAINT `fk_Producto_has_Venta_Producto1`
    FOREIGN KEY (`Producto_Codigo Producto`)
    REFERENCES `mydb`.`Producto` (`Codigo Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Venta_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `mydb`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado_has_Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleado_has_Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleado_has_Persona` (
  `Empleado_idEmpleado` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`Empleado_idEmpleado`, `Persona_idPersona`),
  INDEX `fk_Empleado_has_Persona_Persona1_idx` (`Persona_idPersona` ASC),
  INDEX `fk_Empleado_has_Persona_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Empleado_has_Persona_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Persona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_has_Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto_has_Proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto_has_Proveedor` (
  `Producto_Codigo Producto` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`Producto_Codigo Producto`, `Proveedor_idProveedor`),
  INDEX `fk_Producto_has_Proveedor_Proveedor1_idx` (`Proveedor_idProveedor` ASC),
  INDEX `fk_Producto_has_Proveedor_Producto1_idx` (`Producto_Codigo Producto` ASC),
  CONSTRAINT `fk_Producto_has_Proveedor_Producto1`
    FOREIGN KEY (`Producto_Codigo Producto`)
    REFERENCES `mydb`.`Producto` (`Codigo Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Proveedor_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
